name: stucap_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  barcode_widget:
  equatable:
  bloc:
  flutter_bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          style: normal
          weight: 800
